# .github/workflows/run-shell-script.yml

name: Run Shell Script

on: [push]

jobs:
  run-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Make script executable
        run: chmod +x hello.sh
        
      - name: Run hello.sh
        run: ./hello.sh
